PRR:
    image: "diwo.teranetworks.com:8123/devopshelloimage"  
    container_name:PRR
    hostname:PRR
    restart: always   
    volumes:    
        - /etc/timezone:/etc/timezone:ro   
    
    environment:    
        CASSANDRA_HOST: 10.1.100.53     
        VIRTUOSO_URL: 10.1.100.56:1111   
    command:
         - /tmp/sbt run
         
labels:     
    io.rancher.scheduler.affinity:host_label: hostname=${hostname}     
    io.rancher.container.pull_image: always
         
    