PRR:
    image: "diwo.teranetworks.com:8123/devopshelloimage"
    container_name: PRR
    hostname: PRR
    restart: always
    volumes:
        - /etc/timezone:/etc/timezone:ro
    command:
         - /tmp/sbt run
    labels:
        io.rancher.scheduler.affinity:host_label: hostname=${hostname}
        io.rancher.container.pull_image: always

         
    